capao_digital/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('server_side.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

server_side/urls.py
from django.urls import path

from . import views

app_name = 'authors'

urlpatterns = [
    path('', views.home, name='home'),
    path('register', views.register, name='register'),
    path('register/create', views.create_user, name='create'),

]

server_side/models.py
from django.db import models

# Create your models here.

server_side/forms.py
from django import forms
from django.contrib.auth.models import User


class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'password'
        ]

server_side/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render

from . import forms


def home(req):
    return render(req, 'pages/home.html')


def register(req):

    register_form_data = req.session.get('register_form_data', None)

    form = forms.RegisterForm(register_form_data)

    return render(req, 'pages/register.html', context={
        'form': form
    })


def create_user(req):

    POST = req.POST

    if not POST:
        return HttpResponse('Erro', status=404)
    
    req.session['register_form_data'] = POST
    form = forms.RegisterForm(POST)

    return redirect('authors:register')

server_side/templates/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
<h1>Bem vindo ao capão digital!</h1>

<br>
<br>

<button> <a href="/login">Login</a> </button>
<br><br>
<button> <a href="/register">Cadastre-se</a></button>
{% endblock content %}

server_side/templates/pages/register.html
{% extends 'global/base.html' %}

{% block title %}Register{% endblock title %}

{% block content %}
    <form action=" {% url 'authors:create' %} " method="POST">
        {% csrf_token %}
        <div class="form-content">
            {% for field in form %}
                <div class="form-group">
                    <label for="{{field.id_for_label}}">{{field.label}}</label>
                    {{ field }}
                    {{ field.errors }}
                </div>
            {% endfor %}
        </div>
        <div class="form-group">
            <button type="submit">Enviar</button>
        </div>
    </form>
{% endblock content %}

server_side/templates/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
    integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static '/recipes/css/style.css' %}">